databases:
  - name: campus_hub_db
    databaseName: campus_hub_db
    user: campus_hub_user
    plan: free

services:
  - type: web
    name: campus-hub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn campus_hub.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus_hub_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
